#!/bin/bash

# Submit job scripts generated by fsl_randomise_imgs.sh

# ~/scripts/PPP_imaging/FSL/fsl_randomise_jobsub.sh

statsdir="/project/3024006.02/Analyses/motor_task/Group/Longitudinal/FSL/stats"
logsdir="/project/3024006.02/Analyses/motor_task/Group/Longitudinal/FSL/logs"
# Delta
ses=("delta") # ba fu
# Session
#ses=("ses-Visit1" "ses-Visit2")
for s in ${ses[@]}; do
	# T-test
	jobscripts=( $(ls ${statsdir}/*/cmd_rand_delta_unpaired_ttest_unmatched*.txt) )
	# Delta
	#jobscripts=( $(ls ${statsdir}/*/cmd_rand_delta_clincorr*.txt) )
	# Session
	#jobscripts=( $(ls ${statsdir}/*/by_session/${s}/cmd_rand_*.txt) )
	# Post hoc
	#jobscripts=( $(ls ${statsdir}/*/by_session/${s}/cmd_rand_*.txt) )
	for(( i=0; i<${#jobscripts[@]}; i++ )); do

		JNAME=`basename -- "${jobscripts[i]}" .txt`

		#qsub \
		#	-o ${logsdir} \
		#	-e ${logsdir} \
		#	-N "rand_${s}_${JNAME}" \
		#	-l "nodes=1:ppn=2,walltime=30:00:00,mem=12gb" \
		#	${jobscripts[i]}
			
		sbatch \
			--output ${logsdir}/job.rand.%A_%a.out \
			--error ${logsdir}/job.rand.%A_%a.err \
			--job-name "rand_${s}_${JNAME}" \
			--nodes=1 --cpus-per-task 2 --ntasks-per-node=1 --mem=12G --time=30:00:00 \
			${jobscripts[i]}
			

	done
done
